# update builds and dates, if desired
VERSION=0.9
BUILD=100
DATE=2/07/18

###############
# You may remove these settings if you do not use a third-party oAuth provider.

# This is the RERUM API client id
clientID=62Jsa9MxHuqhRbO20gTHs9KpKr7Ue7sl

#This is the secret.  

#   !!!            DO NOT COMMIT WITH THE SECRET SET                !!
#       !!!        DO NOT COMMIT WITH THE SECRET SET           !!
#           !!!    DO NOT COMMIT WITH THE SECRET SET       !!

rerumSecret=pCHtW13AlWaCCpjw6wcUipG2Vgc2FjWE6_cGEt7VKabfBw-nyqClVY6lsmFBBJsb

#           !!!    DO NOT COMMIT WITH THE SECRET SET      !!
#       !!!        DO NOT COMMIT WITH THE SECRET SET          !!
#   !!!            DO NOT COMMIT WITH THE SECRET SET               !!

#dev-01
bot_agent=http://devstore.rerum.io/v1/id/5b2c0d5de4b0fc5d4aeb709f 

#prod-02
#bot_agent=http://store.rerum.io/v1/id/5b3e3663d5de3ae468582e3e

down=false


###############